services:
  db:
    image: postgres:16
    container_name: digital_library_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 8623
      POSTGRES_DB: digital_library_docker
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: